name: neverlost
description: Time Table, Notes and Todos For Students

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.3.16+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  path: ^1.8.2
  flutter_material_pickers: ^3.3.0
  intl: ^0.17.0
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  file_picker: ^5.2.11
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  open_file_plus: ^3.4.1
  photo_view: ^0.14.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#007DCB"
  image: "assets/logo.png"
  branding: assets/text.png
  branding_mode: bottom

  android_12:
    color: "#007DCB"
    image: "assets/logo.png"
    branding: assets/text.png
    branding_mode: bottom
  android: true
  ios: true
  web: false


# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
